### ISSUE TITLE
Altar inventory size

### ISSUE THREAD

**Issue by SSKirillSS** [TeamDman/ZenSummoning#1]
Hello. Size of summoning altar is infinite? Now you can forget about the chests and put all the things in this altar :D So, can you add an altar capacity limit in the configuration file?

![image](https://user-images.githubusercontent.com/38190325/52882840-fef84c80-3179-11e9-98f7-f67a4c323cf0.png)

**Comment by TeamDman** [comment]
Currently it's hardcoded as a 256 slot inventory, will probably just make it dynamic to the largest size recipe registered

**Comment by TeamDman** [comment]
Fixed in  8816788 
Build will be on CurseForge shortly
